version: '3'
services:
  www:
    build:
      context: ./interspeedtest
      dockerfile: Dockerfile
    container_name: phpweb
    volumes:
      - ./interspeedtest:/var/www/html
    depends_on:
      - db
    ports:
      - "8080:80"
  
  db:
    container_name: db
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
    env_file:
      - ./config.env
    ports:
      - "3306:3306"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8088:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    restart: always
    env_file:
      - ./config.env
    depends_on:
      - db

  snmp:
    build:
      context: ./snmp
      dockerfile: Dockerfile
    container_name: snmp
    restart: always
    volumes:
      - ./snmp:/app
    depends_on:
      - db

volumes:
    persistent:



