version: '3'
services:
  www:
    build:
      context: ./interspeedtest
      dockerfile: Dockerfile
    container_name: phpweb
    volumes:
      - ./interspeedtest:/var/www/html
    depends_on:
      - db
    ports:
      - "8080:80"
  
  db:
    container_name: db
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
    env_file:
      - ./config.env
    ports:
      - "3308:3306"

  laravel:
    build:
      context: ./speedtest-admin
      dockerfile: Dockerfile
    container_name: adminweb
    volumes:
      - ./

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    restart: always
    env_file:
      - ./config.env
    depends_on:
      - db
volumes:
    persistent:



